/* MTI_DPI */

/*
 * Copyright 2002-2017 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linuxpe'
 */
#ifndef INCLUDED_HELLO
#define INCLUDED_HELLO

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
void
hello();

DPI_LINK_DECL DPI_DLLESPEC
double
sin(
    double in);

#endif 
