function y = cicfilter(f, x, phase)
%CICFILTER N-stage decimate by R CIC-filter design
%  Y = CICFILTER(F, X) filters the data in vector X with the CIC filter
%  described by F to create the filtered data Y.
%
%  where:
%  F is the filter designed by CICDESIGN
%  X is the input vector to be filtered
%  
%  The filter, F, should have been generated by the CICDESIGN function.
%
%  Author: Shen-Hsiao TAN
%  Date  : Oct 09
%

y = filter(f.B, f.A, x);
y = downsample(y, f.R, phase);
